// AUTO-GENERATED BY INGESTION SCRIPT
// Represents the Saudi Sign Language (SSL) procedural definitions

export interface SignEntry {
  english: string;
  arabic?: string;
  handshape?: string;
  movement?: string;
  location?: string;
  nonManual?: string;
  duration?: number;
}

export const SSL_SIGNS: Record<string, SignEntry> = {
  "MABROUK": {
    "english": "Congratulations",
    "arabic": "مبروك",
    "handshape": "flat",
    "movement": "circular_forward",
    "location": "chest",
    "duration": 2500
  },
  "SHUKRAN": {
    "english": "Thank you",
    "arabic": "شكرا",
    "handshape": "flat",
    "movement": "forward",
    "location": "mouth",
    "duration": 1500
  },
  "KEF_HALAK": {
    "english": "How are you",
    "arabic": "كيف حالك",
    "handshape": "point",
    "movement": "up_down",
    "location": "neutral",
    "duration": 3000
  },
  "NAAM": {
    "english": "Yes",
    "arabic": "نعم",
    "handshape": "fist",
    "movement": "nod_hand",
    "location": "neutral",
    "duration": 1200
  },
  "LA": {
    "english": "No",
    "arabic": "لا",
    "handshape": "point",
    "movement": "shake_hand",
    "location": "neutral",
    "duration": 1200
  }
};
