import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

async function main() {
  console.log('Generating SSL Sign Database for the Avatar Engine...');

  const annotations = await prisma.datasetAnnotation.findMany({
    where: {
      video: {
        dataset: {
          name: { contains: 'Saudi Sign Language' }
        }
      }
    },
    include: {
      video: true
    }
  });

  const dbEntries: Record<string, any> = {};

  for (const ann of annotations) {
    if (!ann.gestureLabel) continue;
    
    // In our simplified pipeline, landmarksJson contains the procedural handshape details
    const landmarks = JSON.parse(ann.landmarksJson);
    
    dbEntries[ann.gestureLabel.toUpperCase()] = {
      english: ann.sentenceLabel || ann.gestureLabel,
      arabic: ann.sentenceLabel,
      handshape: landmarks.handshape || 'flat',
      movement: landmarks.movement || 'neutral',
      location: landmarks.location || 'neutral',
      duration: ann.video.durationMs || 1000,
    };
  }

  const fileContent = `// AUTO-GENERATED BY INGESTION SCRIPT
// Represents the Saudi Sign Language (SSL) procedural definitions

export interface SignEntry {
  english: string;
  arabic?: string;
  handshape?: string;
  movement?: string;
  location?: string;
  nonManual?: string;
  duration?: number;
}

export const SSL_SIGNS: Record<string, SignEntry> = ${JSON.stringify(dbEntries, null, 2)};
`;

  const outputPath = path.join(__dirname, '../../../apps/web/src/lib/avatar/ssl-sign-database.ts');
  fs.writeFileSync(outputPath, fileContent, 'utf-8');

  console.log(`Successfully generated SSL database with ${annotations.length} signs at: ${outputPath}`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('Generation Failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
